class Watchdog:
    TIMER_USE_BIOS_FRB2 = 1
    TIMER_USE_BIOS_POST = 2
    TIMER_USE_OS_LOAD   = 3
    TIMER_USE_SMS_OS    = 4
    TIMER_USE_OEM       = 5

    TIMEOUT_ACTION_NO_ACTION   = 0
    TIMEOUT_ACTION_HARD_RESET  = 1
    TIMEOUT_ACTION_POWER_DOWN  = 2
    TIMEOUT_ACTION_POWER_CYCLE = 3
