class Bmc:
    BMC_WATCHDOG_TIMER_USE_BIOS_FRB2 = 1
    BMC_WATCHDOG_TIMER_USE_BIOS_POST = 2
    BMC_WATCHDOG_TIMER_USE_OS_LOAD   = 3
    BMC_WATCHDOG_TIMER_USE_SMS_OS    = 4
    BMC_WATCHDOG_TIMER_USE_OEM       = 5

    BMC_WATCHDOG_TIMEOUT_ACTION_NO_ACTION   = 0
    BMC_WATCHDOG_TIMEOUT_ACTION_HARD_RESET  = 1
    BMC_WATCHDOG_TIMEOUT_ACTION_POWER_DOWN  = 2
    BMC_WATCHDOG_TIMEOUT_ACTION_POWER_CYCLE = 3
