WATCHDOG_TIMER_USE_BIOS_FRB2 = 1
WATCHDOG_TIMER_USE_BIOS_POST = 2
WATCHDOG_TIMER_USE_OS_LOAD   = 3
WATCHDOG_TIMER_USE_SMS_OS    = 4
WATCHDOG_TIMER_USE_OEM       = 5

WATCHDOG_TIMEOUT_ACTION_NO_ACTION   = 0
WATCHDOG_TIMEOUT_ACTION_HARD_RESET  = 1
WATCHDOG_TIMEOUT_ACTION_POWER_DOWN  = 2
WATCHDOG_TIMEOUT_ACTION_POWER_CYCLE = 3
